### ISSUE TITLE
duplicate v1 uuids if both msecs and nsecs are specified

### ISSUE THREAD

**Issue by winglian** [broofa/node-uuid#139]
if we were to repeatedly try to get uuids for the exact same msecs and nsecs `uuid.v1({msecs: 1461468815517, nsecs: 1234})`, it would return the exact same uuid since this line (https://github.com/broofa/node-uuid/blob/master/uuid.js#L158) only checks for `<`, although a non-moving clock might be considered a clock regression too. For example if you were to subsequently decrement the nsecs in the next call and re-increment it back to the first value on subsequent calls, it would have a different UUID due to a clock sequence change. Would it be a violation of the RFC to use `<=` comparison here?

**Comment by broofa** [comment]
A non-moving clock isn't a regression, it's simply what happens when the frequency of the clock is less than the frequency of v1() invocations.  This case is addressed in the RFC:

> A high resolution timestamp can be simulated by keeping a count of the number of UUIDs that have been generated with the same value of the system time, and using it to construct the low order bits of the timestamp.

By specifying `nsecs` explicitly you're overriding the mechanism used to ensure UUID uniqueness in this case.  Thus, duplicate UUIDs are expected.  (If that seems wrong to you, bear in mind that the `options` argument is supported primarily for testing purposes.  It's not something you should be using in non-testing situations.)
