### ISSUE TITLE
uuid.v4() different on two different devices

### ISSUE THREAD

**Issue by serganus** [broofa/node-uuid#147]
I am thinking to use it as secret for some auth components and is worried if uuid.4() is same on different machines?

I understand uuid.1() won't work as it uses timestamp but is it true for uuid.v4()?

**Comment by r24y** [comment]
A Version 4 UUID is entirely randomly-generated. This should be different on different machines, but if you're generating a lot of UUIDs (truly huge numbers) there's a chance of collision. However, in practice this is _extremely_ unlikely, and you also benefit from the IDs being unpredictable (assuming your RNG/PRNG is a good one).

If your machine IDs are guaranteed to be different, then you will not generate the same Version 1 UUID on multiple machines. However, if you're using V1 IDs as an application secret, be aware that it drastically reduces the search space required for someone trying to break your security, since they can infer the timestamp information and perhaps even guess machine ID.

This question is not specific to this library; rather, it would be beneficial to study V1 vs V4 UUIDs in general and determine which better meets your needs. Check out for instance [this Stack Overflow question](http://stackoverflow.com/questions/20342058/which-uuid-version-to-use).

**Comment by broofa** [comment]
v1 ids include a randomly generated "node" id (47 randomly generated bits) to mitigate the chance of a collision, even if the system timestamps are identical.  The node is a 47-bit value, even in the case of two processes that happen to generate ids at exactly the same 100-nanosecond time - i.e. where all the non-node bits are identical, there's still only a ~1:281 trillion chance the ids will collide.

v4 ids are randomly generated, so there's a 1-in-2^^122 chance of any two ids colliding... assuming a "high quality" random number generator (rng).

In practice as long as you're clients are running on [systems where node-uuid uses the `crypto`](http://caniuse.com/#feat=cryptography) API as the source of random #'s, the odds of collision are incredibly small with either v1() or v4().  (Nonetheless, it's always a good idea to check for collisions in case there's an undiscovered bug somewhere that compromises the uniqueness of ids.)
